### PR TITLE
Remove includes

### PR DESCRIPTION
**Pull request by GregKass**

### CODE REVIEW

**Comment by chris--jones** [comment]
Won't the includes become indexOf or similar during transpilation anyway?

Are there reservations about using ES7 syntax?

**Comment by GregKass** [comment]
If you use ES7 syntax, you'll have to specifically use an ES7 transpiler. This is extra work for anyone wishing to use the plugin and adds a lot of extra transpiler code to achieve one array method that can easily be accomplished using `indexof`

**Comment by chris--jones** [comment]
I concur

**Comment by anandSep90** [comment]
please commit the fix. it will be very much appreciated.

**Pull request merged**
